insert into PRODUCT_INVENTORY values (1, TRUE, 'Iphone', 'Iphone', 100)
insert into PRODUCT_INVENTORY values (2, TRUE, 'Redmi', 'Redmi', 100)
insert into PRODUCT_INVENTORY values (3, FALSE, 'Moto', 'Moto', 0)
insert into PRODUCT_INVENTORY values (4, TRUE, 'OnePlus', 'OnePlus', 100)
insert into PRODUCT_INVENTORY values (5, TRUE, 'Samsung', 'Samsung', 100)
insert into PRODUCT_INVENTORY values (6, FALSE, 'Google', 'Pixel', 0)
insert into PRODUCT_INVENTORY values (7, TRUE, 'LG', 'G7', 2)